package ru.imaginaerum.wd.common.init.tab;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.registries.DeferredRegister;
import ru.imaginaerum.wd.WD;
import ru.imaginaerum.wd.common.init.items.ItemsWD;

import java.util.function.Supplier;

public class TabsWD {
    public static final DeferredRegister<CreativeModeTab> TABS_WD =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, WD.MOD_ID);

    public static final Supplier<CreativeModeTab> WD_TAB = TABS_WD.register("tabs_wd",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ItemsWD.JAR.get()))
                    .title(Component.translatable("creativetab.wd.tabs"))
                    .displayItems((itemDisplayParameters, output) -> {
                        output.accept(ItemsWD.COASTAL_STEEP);
                        output.accept(ItemsWD.COASTAL_STEEP_FIBERS);
                        output.accept(ItemsWD.COASTAL_STEEP_FLOWER);
                        output.accept(ItemsWD.POISON_BERRY);
                        output.accept(ItemsWD.CHARMING_BERRIES);
                        output.accept(ItemsWD.FIRE_STEM);
                        output.accept(ItemsWD.FREEZE_BERRIES);
                        output.accept(ItemsWD.ROSE_OF_GHOSTY_TEARS);
                        output.accept(ItemsWD.ROSE_OF_THE_MURDERER);
                        output.accept(ItemsWD.MEADOW_GOLDEN_FLOWER);
                        output.accept(ItemsWD.JAR);
                        output.accept(ItemsWD.POISON_BERRY_JAM);
                        output.accept(ItemsWD.CHARMING_JAM);
                        output.accept(ItemsWD.APPLE_JAM);
                        output.accept(ItemsWD.SWEET_JAM);
                        output.accept(ItemsWD.FREEZE_JAM);
                        output.accept(ItemsWD.JAM_TONIC);
                        output.accept(ItemsWD.JAM_INVISIBILITY);
                        output.accept(ItemsWD.LEVITAN_JAM);
                        output.accept(ItemsWD.GLOWING_JAM);
                        output.accept(ItemsWD.SUGAR_REFINED);
                        output.accept(ItemsWD.RAW_WAFFLES);
                        output.accept(ItemsWD.WAFFLES);
                        output.accept(ItemsWD.APPLE_WAFFLES);
                        output.accept(ItemsWD.BERRIES_WAFFLES);
                        output.accept(ItemsWD.GLOW_BERRIES_WAFFLES);
                        output.accept(ItemsWD.ICE_WAFFLES);
                        output.accept(ItemsWD.CHARMING_WAFFLES);
                        output.accept(ItemsWD.POISON_WAFFLES);
                        output.accept(ItemsWD.SPATIAL_ORCHID);
                        output.accept(ItemsWD.THE_PILLAGERS_CHEST);
                        output.accept(ItemsWD.GOLDEN_CHEST_KING_PILLAGER);
                        output.accept(ItemsWD.THE_PILLAGERS_KEY);
                        output.accept(ItemsWD.THE_KING_PILLAGERS_KEY);
                        output.accept(ItemsWD.A_DROP_OF_LOVE);
                        output.accept(ItemsWD.HEALING_DEW);
                        output.accept(ItemsWD.NETHER_GROG);
                        output.accept(ItemsWD.SPARKLING_POLLEN);
                        output.accept(ItemsWD.GRASS_BONE_MEAL);
                        output.accept(ItemsWD.CRIMSON_BONE_MEAL);
                        output.accept(ItemsWD.WARPED_BONE_MEAL);
                        output.accept(ItemsWD.MYCELIUM_BONE_MEAL);
                        output.accept(ItemsWD.DRAGOLIT_INGOT);
                        output.accept(ItemsWD.CLEAR_DRAGOLIT_NUGGET);
                        output.accept(ItemsWD.STRANGE_SCRAP);
                        output.accept(ItemsWD.RAW_GOATS_MEAT);
                        output.accept(ItemsWD.GOAT_MEAT_KEBAB);
                        output.accept(ItemsWD.RAW_SLICING_GOATS_MEAT);
                        output.accept(ItemsWD.RAW_BEAR_MEAT);
                        output.accept(ItemsWD.COOKED_GOAT_MEAT_KEBAB);
                        output.accept(ItemsWD.CAMEL_MEAT_KEBAB);
                        output.accept(ItemsWD.COOKED_CAMEL_MEAT_KEBAB);
                        output.accept(ItemsWD.RAW_HORSE);
                        output.accept(ItemsWD.COOKED_HORSE);
                        output.accept(ItemsWD.RAW_CAMEL_MEAT);
                        output.accept(ItemsWD.COOKED_CAMEL_MEAT);
                        output.accept(ItemsWD.RAW_SLICING_CAMEL_MEAT);
                        output.accept(ItemsWD.COOKED_SLICING_CAMEL_MEAT);
                        output.accept(ItemsWD.COOKED_SLICING_GOATS_MEAT);
                        output.accept(ItemsWD.COOKED_BEAR_MEAT);
                        output.accept(ItemsWD.COOKED_GOATS_MEAT);
                        output.accept(ItemsWD.GOATS_MEAT_PILAF);
                        output.accept(ItemsWD.WIZARD_PIE_SLICE);
                        output.accept(ItemsWD.ROTTEN_PIE_SLICE);
                        output.accept(ItemsWD.FROG_BODY);
                        output.accept(ItemsWD.FROG_LEGS);
                        output.accept(ItemsWD.COOKED_FROG);
                        output.accept(ItemsWD.COOKED_FROG_LEGS);
                        output.accept(ItemsWD.GOULASH_WITH_GOAT_MEAT);
                        output.accept(ItemsWD.POT);
                        output.accept(ItemsWD.POT_FROM_MEAT_GOAT);
                        output.accept(ItemsWD.POT_FROM_MEAT_CAMEL);
                        output.accept(ItemsWD.MARINADED_POT_FROM_MEAT_CAMEL);
                        output.accept(ItemsWD.MARINADED_POT_FROM_MEAT_GOAT);
                        output.accept(ItemsWD.SWEET_ROLL);
                        output.accept(ItemsWD.SPAGETTI_IN_THE_NORTH);
                        output.accept(ItemsWD.ROAST_GOAT_MEAT_WITH_FREEZE_BERRIES_SYRUP);
                        output.accept(ItemsWD.BEAR_MEAT_SOUP);
                        output.accept(ItemsWD.MEDICAL_POTATO);
                        output.accept(ItemsWD.BRIGHT_PEPPER);
                        output.accept(ItemsWD.KRUTNEVY_BREAD);
                        output.accept(ItemsWD.TURTLE_SOUP);
                        output.accept(ItemsWD.CLEANED_TURTLE_NECK);
                        output.accept(ItemsWD.PICKLED_TURTLE_NECK);
                        output.accept(ItemsWD.TURTLE_NECK);
                        output.accept(ItemsWD.HOT_COCOA_WITH_SPARKING_POLLEN);
                        output.accept(ItemsWD.HUNTING_TWISTER);
                        output.accept(ItemsWD.IRIS);
                        output.accept(ItemsWD.MUSHROOM_ON_STICK);
                        output.accept(ItemsWD.COOKED_MUSHROOM_ON_STICK);
                        output.accept(ItemsWD.SHPIKACHKI);
                        output.accept(ItemsWD.COOKED_SHPIKACHKI);
                        output.accept(ItemsWD.DUNGEON_MASTER_CHEESE);
                        output.accept(ItemsWD.WIZARD_PIE);
                        output.accept(ItemsWD.ROTTEN_PIE);
                        output.accept(ItemsWD.SUGAR_SACK);
                        output.accept(ItemsWD.DRAGOLIT_BLOCK);
                        output.accept(ItemsWD.DRAGOLIT_GRID);
                        output.accept(ItemsWD.STRANGE_CHIP);
                        output.accept(ItemsWD.A_BLOCK_OF_SPARKLING_POLLEN);
                        output.accept(ItemsWD.IRON_WATERING_CAN);
                        output.accept(ItemsWD.MAGIC_SOIL);
                        output.accept(ItemsWD.MAGIC_SOIL_FARMLAND);
                        output.accept(ItemsWD.MAGIC_SOIL_GRASS);
                        output.accept(ItemsWD.BRIGHT_PEPPER_SEEDS);
                        output.accept(ItemsWD.SILVERAN);
                        output.accept(ItemsWD.HANDFUL_NETHER);
                        output.accept(ItemsWD.HANDFUL_YADOGA);
                        output.accept(ItemsWD.CLEANSING_DECOCTION);
                        output.accept(ItemsWD.SOUL_STONE);
                        output.accept(ItemsWD.DRAGOLIT_RAPIER);
                        output.accept(ItemsWD.ROBIN_STICK);
                        output.accept(ItemsWD.DRAGOLITE_CAGE);
                    }).build());
}
